version: "3"

services:
  php:
    build:
      context: bin/php
    container_name: '${PROJECT_NAME}-php'
    restart: 'always'
    ports:
      - ${PHP_HTTP_PORT}:80
    links:
      - mysql
    volumes:
      - ${DOCUMENT_ROOT}:/var/www/html
      - ${PHP_INI}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR}:/etc/apache2/sites-available
      - ${APACHE_LOG_DIR}:/var/log/apache2
      - ${BASH_RC}:/root/.bashrc
    environment:
      DB_HOST: ${MYSQL_HOST}
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
  mysql:
    build:
      context: bin/mysql
    container_name: '${PROJECT_NAME}-mysql'
    restart: 'always'
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
      - ${MYSQL_LOG_DIR}:/var/log/mysql
      - ${MYSQL_INIT_DIR}:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
